name: Deploy to Firebase Hosting on PR

on:
  pull_request:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting (Preview)
        id: firebase_deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          projectId: afortu

      - name: Comment preview URL on PR
        if: ${{ steps.firebase_deploy.outputs.details_url }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            🚀 Preview desplegado en Firebase Hosting: [Ver Preview](${{ steps.firebase_deploy.outputs.details_url }})
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}